### ISSUE TITLE
Which version of Cuda/CUDNN to use?

### ISSUE THREAD

**Issue by rowanz** [CMU-Perceptual-Computing-Lab/caffe_rtpose#9]
I'm trying to get the forked version of caffe to compile, but am unable to pass the tests or run the model. In either case, I have the same error: Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

For reference, I'm on Ubuntu 16.04.01. I've tried a couple of different cudnn/cuda configs but seem to get that error each time. I've also successfully built a couple of other caffe / forked caffe versions on this machine, without seeing this error.

Anyways, for reference, what versions of cuda/cudnn have been successful? Thanks!

**Comment by rowanz** [comment]
nevermind! I was able to get it to work by changing the library dirs line in the Makefile to 

LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

Weird why that worked. Closing this issue now...
